### ISSUE TITLE
TypeError: Object #<Object> has no method 'createFile'

### ISSUE THREAD

**Issue by clochix** [cozy/jsDAV#19]
Sync crash with the following error:

```
Exception:  { [Error: Could not find node at path: principals/me/726c57a3-270d-4123-8ee7-f665909f217d.ics]
  code: 404,
  type: 'FileNotFound',
  message: 'Could not find node at path: principals/me/726c57a3-270d-4123-8ee7-f665909f217d.ics' }

TypeError: Object #<Object> has no method 'createFile'
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:2306:40
    at readDone (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:1334:13)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:1298:25
    at Object.req.streambuffer.onend (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/util.js:850:17)
    at getRequestBody (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:1280:30)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:2302:34
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:75:13
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:371:33)
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:146:21)
    at Object.next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:451:13)
Exception:  { [Error: Could not find node at path: principals/me/726c57a3-270d-4123-8ee7-f665909f217d.ics]
  code: 404,
  type: 'FileNotFound',
  message: 'Could not find node at path: principals/me/726c57a3-270d-4123-8ee7-f665909f217d.ics' }
```

**Comment by clochix** [comment]
I saw this error in the logs sent by another user who has problem when trying to sync its calendar with Thunderbird. Sorry, no more context.

**Comment by clochix** [comment]
Another user is having this issue, which prevent him from syncing its calendar

**Comment by clochix** [comment]
Here are some logs, after adding a patch that prevent the application from crashing:
<detail>

```
PUT /public/principals/me/fd93d51c-d4eb-410d-ad2b-55561057ac49.ics HTTP/1.1
cache-control: no-cache
pragma: no-cache
authorization: Basic bWU6eDFIclBISlZjZg==
if-none-match: *
content-type: text/calendar; charset=utf-8
accept-charset: utf-8,*;q=0.1
dnt: 1
accept-encoding: gzip, deflate
accept-language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
accept: text/xml
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Thunderbird/45.4.0 Lightning/4.7.4
content-length: 722
host: 10.240.2.103:9104
connection: upgrade


BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20161017T165646Z
LAST-MODIFIED:20161017T165705Z
DTSTAMP:20161017T165705Z
UID:fd93d51c-d4eb-410d-ad2b-55561057ac49
SUMMARY:CozyTest Thunder
DTSTART;TZID=Europe/Paris:20161018T190000
DTEND;TZID=Europe/Paris:20161018T200000
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/xml; charset=utf-8
Date: Wed, 19 Oct 2016 14:08:19 GMT
Connection: keep-alive
Transfer-Encoding: chunked

101
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:a="http://ajax.org/2005/aml">
    <a:exception>jsDAV_Exception</a:exception>
    <a:message>parent has no createFile method</a:message>
<a:jsdav-version>0.3.16</a:jsdav-version>
</d:error>

```

</detail>
