### ISSUE TITLE
TypeError: self.handler.getHTTPPRefer is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/jsDAV#22]
TypeError: self.handler.getHTTPPRefer is not a function
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAVACL/plugin.js:1429:39
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAVACL/plugin.js:724:25
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:371:33)
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:146:21)
    at Object.next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:451:13)
    at next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:144:20)
    at __dirname.end (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:368:16)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAVACL/plugin.js:723:22
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:371:33)
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:146:21)

**Comment by poupotte** [comment]
Thanks @clochix :)
