### ISSUE TITLE
TypeError: Object #<Object> has no method 'addressBookQueryReport'

### ISSUE THREAD

**Issue by clochix** [cozy/jsDAV#6]
When trying to sync contacts:
```
TypeError: Object #<Object> has no method 'addressBookQueryReport'
    at Object.module.exports.jsDAV_Plugin.extend.report (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/CardDAV/plugin.js:281:22)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:57:22
    at handler (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:148:21)
    at Object.next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:449:13)
    at next (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:144:20)
    at end (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/node_modules/asyncjs/lib/async.js:368:16)
    at dispatchEvent (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/asyncEvents.js:67:12)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:1166:22
    at Object.exports.loadDOMDocument (/usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/shared/xml.js:187:5)
    at /usr/local/cozy/apps/sync/node_modules/cozy-jsdav-fork/lib/DAV/handler.js:1164:17
```

**Comment by poupotte** [comment]
This issue is now fixed.
